export type StorefrontConfiguration = {
  configuration_id?: string | null;
  configuration_price_id?: string | null;
  source_price_row_id?: string | null;
  sellable_configuration_id?: string | null;
  configuration_label?: string | null;
  configuration_name?: string | null;
  option_name?: string | null;
  option_value?: string | null;
  raw_option_value?: string | null;
  raw_option_text?: string | null;
  title?: string | null;
  label?: string | null;
  price_amount?: number | null;
  price?: number | null;
  amount?: number | null;
  min_price?: number | null;
  max_price?: number | null;
  currency?: string | null;
  has_fallback_price?: boolean | null;
  sort_order?: number | null;
  components?: unknown;
  selected_options?: unknown;
  [key: string]: unknown;
};

export type StorefrontMedia = {
  position?: number | null;
  media_type?: 'image' | 'video' | string | null;
  url?: string | null;
  alt?: string | null;
  is_primary?: boolean | null;
  [key: string]: unknown;
};

export type StorefrontProduct = {
  canonical_product_id: string;
  product_slug: string | null;
  matched_etsy_listing_id: string | null;
  source_url: string | null;
  card_title: string | null;
  h1: string | null;
  seo_title: string | null;
  meta_description: string | null;
  product_type: string | null;
  material: string | null;
  color: string | null;
  size_mode: string | null;
  production_profile: string | null;
  shipping_profile: string | null;
  handmade_flag: boolean | null;
  styled_imagery_flag: boolean | null;
  primary_image_url: string | null;
  primary_image_alt: string | null;
  secondary_image_url?: string | null;
  hover_image_url?: string | null;
  video_url?: string | null;
  media_gallery?: StorefrontMedia[] | unknown;
  media_count?: number | null;
  has_video?: boolean | null;
  min_price: number | null;
  max_price: number | null;
  currency: string | null;
  has_fallback_price: boolean | null;
  has_sampler_excluded_price: boolean | null;
  public_configuration_count: number | null;
  public_price_row_count: number | null;
  pdp_option_count?: number | null;
  has_multiple_pdp_options?: boolean | null;
  configurations: StorefrontConfiguration[] | unknown;
  storefront_candidate_flag: boolean | null;
};

export type ReviewQueueSummary = {
  queue_code?: string | null;
  queue_name?: string | null;
  status?: string | null;
  review_queue?: string | null;
  item_count?: number | null;
  count?: number | null;
  row_count?: number | null;
  total?: number | null;
  priority?: number | null;
  description?: string | null;
  [key: string]: unknown;
};

export type AdminCatalogRow = {
  canonical_product_id: string;
  matched_etsy_listing_id?: string | null;
  etsy_listing_id?: string | null;
  draft_site_title?: string | null;
  card_title?: string | null;
  h1?: string | null;
  source_title?: string | null;
  raw_title?: string | null;
  readiness_status?: string | null;
  readiness_label?: string | null;
  status?: string | null;
  publish_status?: string | null;
  storefront_status?: string | null;
  publication_status?: string | null;
  next_action?: string | null;
  notes?: string | null;
  review_reason?: string | null;
  blocker_reason?: string | null;
  do_not_publish_flag?: boolean | null;
  [key: string]: unknown;
};


export type SeoKeywordCleanupReportRow = {
  keyword?: string | null;
  keyword_norm?: string | null;
  priority_tier?: string | null;
  queue_suggested_page_level?: string | null;
  queue_keyword_axis?: string | null;
  queue_keyword_pattern?: string | null;
  validation_status?: string | null;
  cleanup_pipeline_status?: string | null;
  cleaned_keyword?: string | null;
  suggested_keyword?: string | null;
  should_validate_api?: boolean | null;
  should_hold?: boolean | null;
  needs_ai_cleanup?: boolean | null;
  needs_human_review?: boolean | null;
  ready_for_metric_validation?: boolean | null;
  warning_flags?: string[] | string | null;
  [key: string]: unknown;
};
