// @ts-nocheck
import Link from 'next/link';
import { ArrowUpRight, CheckCircle2, DatabaseZap, FileText, Gauge, Layers3, Search, ShieldAlert, Sparkles } from 'lucide-react';
import { getMissingSupabaseEnvMessage, getSupabaseReadClient } from '@/lib/supabase';
import { STOREFRONT_VIEW_V1, productSlug, productTitle } from '@/lib/storefront';
import { buildSeoPilotBrief } from '@/lib/seoPilotDraft';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

const PRODUCT_SELECT = 'canonical_product_id,product_slug,matched_etsy_listing_id,card_title,h1,product_type,material,color,primary_image_url,min_price,max_price,currency,storefront_candidate_flag';
const KEYWORD_SELECT = 'keyword,keyword_norm,priority_tier,validation_status,cleanup_pipeline_status,should_validate_api,should_hold,warning_flags';
const FALLBACK_PRODUCT = { canonical_product_id: '4511817111', product_slug: 'gold-futuristic-armor-set-choker-collar-shoulder-armor-and-arm-bracers-performance-outfit-4511817111', matched_etsy_listing_id: '4511817111', card_title: 'Gold Futuristic Armor Set, Choker Collar, Shoulder Armor and Arm Bracers, Performance Outfit', h1: 'Gold Futuristic Armor Set, Choker Collar, Shoulder Armor and Arm Bracers, Performance Outfit', product_type: 'Armor', material: 'Fabric, Leather, Faux leather', color: 'Gold', primary_image_url: null, min_price: 79, max_price: 308, currency: 'EUR', storefront_candidate_flag: true };

function keyOf(product) { return String(product?.canonical_product_id || product?.matched_etsy_listing_id || productSlug(product) || ''); }
function isSelected(product, selected) { return selected && [product?.canonical_product_id, product?.matched_etsy_listing_id, productSlug(product)].filter(Boolean).map(String).includes(String(selected)); }
function searchText(product) { return [productTitle(product), product?.h1, product?.product_type, product?.material, product?.color, keyOf(product), productSlug(product)].filter(Boolean).join(' ').toLowerCase(); }
function queryFor(productId, q) { const params = new URLSearchParams(); if (productId) params.set('product', productId); if (q) params.set('q', q); const value = params.toString(); return value ? `?${value}` : ''; }
async function loadData(selectedProductId, q) {
  const supabase = getSupabaseReadClient();
  if (!supabase) return { product: FALLBACK_PRODUCT, products: [FALLBACK_PRODUCT], allCount: 1, keywords: [], warning: getMissingSupabaseEnvMessage(), fallbackUsed: true };
  const productsResult = await supabase.from(STOREFRONT_VIEW_V1).select(PRODUCT_SELECT).limit(160);
  const allProducts = (productsResult.data || []).filter((item) => productSlug(item) && productTitle(item));
  const needle = String(q || '').trim().toLowerCase();
  const filteredProducts = needle ? allProducts.filter((item) => searchText(item).includes(needle)) : allProducts;
  const product = allProducts.find((item) => isSelected(item, selectedProductId)) || filteredProducts[0] || allProducts[0] || FALLBACK_PRODUCT;
  const keywordsResult = await supabase.from('feya_commerce_v_seo_keyword_ai_cleanup_report_v1').select(KEYWORD_SELECT).eq('priority_tier', 'tier_1').limit(80);
  return { product, products: filteredProducts.length ? filteredProducts : allProducts.slice(0, 24), allCount: allProducts.length, keywords: keywordsResult.data || [], warning: productsResult.error?.message || keywordsResult.error?.message || null, fallbackUsed: !allProducts.length };
}
function tone(status) { if (status === 'готово') return 'border-[rgba(108,183,138,.35)] text-[#a9dfbd] bg-[rgba(108,183,138,.08)]'; if (status === 'блокер') return 'border-[rgba(196,64,88,.34)] text-[var(--ruby-soft)] bg-[rgba(160,32,56,.08)]'; return 'border-[rgba(212,178,106,.30)] text-[var(--gold-warm)] bg-[rgba(212,178,106,.07)]'; }
function Chip({ children, status = 'ожидает' }) { return <span className={`inline-flex rounded-full border px-2 py-0.5 text-[9px] uppercase tracking-[0.14em] ${tone(status)}`}>{children}</span>; }
function Panel({ title, children, icon: Icon }) { return <div className="rounded-2xl border border-[rgba(216,214,211,.12)] bg-[rgba(255,255,255,.025)] overflow-hidden"><div className="flex items-center justify-between gap-4 px-4 py-3 border-b border-[rgba(216,214,211,.10)]"><div className="eyebrow-gold">{title}</div>{Icon ? <Icon size={16} className="text-[var(--gold-warm)]" /> : null}</div><div className="p-4">{children}</div></div>; }
function SearchBox({ q }) { return <form action="/admin/seo-engine/studio" className="mb-3 grid md:grid-cols-[1fr_auto_auto] gap-2"><div className="relative"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--smoke)]" /><input name="q" defaultValue={q} placeholder="Поиск: armor, choker, gold, bodysuit, ID, материал..." className="w-full rounded-xl border border-[rgba(216,214,211,.12)] bg-black/25 pl-9 pr-3 py-2.5 text-[12px] text-bone outline-none focus:border-[rgba(212,178,106,.45)]" /></div><button className="btn-ghost" type="submit">Найти</button><Link href="/admin/seo-engine/studio" className="btn-ghost">Сбросить</Link></form>; }
function ProductGrid({ products, activeKey, q }) { return <div className="grid md:grid-cols-2 xl:grid-cols-4 gap-2">{products.slice(0, 24).map((item) => { const key = keyOf(item); const active = key === activeKey; return <Link key={key} href={`/admin/seo-engine/studio${queryFor(key, q)}`} className={`rounded-xl border p-3 transition-colors ${active ? 'border-[rgba(212,178,106,.55)] bg-[rgba(212,178,106,.08)]' : 'border-[rgba(216,214,211,.10)] bg-black/15 hover:border-[rgba(212,178,106,.30)]'}`}><div className="text-bone text-[11px] leading-snug line-clamp-2">{productTitle(item)}</div><div className="mt-2 flex items-center justify-between gap-2"><span className="text-[9px] text-[var(--smoke)]">ID {key}</span>{active ? <Chip status="готово">выбран</Chip> : <span className="text-[9px] text-[var(--gold-warm)]">выбрать</span>}</div></Link>; })}</div>; }
function Step({ item }) { return <Link href={item.href} className="block rounded-2xl border border-[rgba(216,214,211,.12)] bg-[rgba(255,255,255,.025)] p-4 hover:border-[rgba(212,178,106,.35)]"><div className="flex items-start justify-between gap-3"><div><div className="text-bone text-[14px] leading-snug">{item.title}</div><div className="mt-1 text-[10px] uppercase tracking-[0.16em] text-[var(--smoke)]">{item.subtitle}</div></div><item.icon size={16} className="text-[var(--gold-warm)]" /></div><div className="mt-3"><Chip status={item.status}>{item.status}</Chip></div><div className="mt-3 text-[11px] leading-relaxed text-[var(--bone-dim)]">{item.description}</div></Link>; }

export default async function SeoContentStudioPage({ searchParams }) {
  const params = await searchParams;
  const selectedProductId = params?.product || '';
  const q = String(params?.q || '').trim();
  const { product, products, allCount, keywords, warning, fallbackUsed } = await loadData(selectedProductId, q);
  const activeKey = keyOf(product);
  const brief = buildSeoPilotBrief(product, keywords);
  const productReady = brief.blockerChecks.filter((item) => item.status === 'blocker').length === 0;
  const query = queryFor(activeKey, q);
  const steps = [
    { title: '1. Товар', subtitle: 'ДНК и факты', status: productReady ? 'готово' : 'блокер', icon: FileText, href: `/admin/seo-engine/briefs${query}`, description: 'Проверяем реальные детали, цвет, материал, цену, фото и запретные обещания.' },
    { title: '2. Ключи', subtitle: 'seed + semantic map', status: brief.metricValidationPackage.length ? 'готово' : 'блокер', icon: Layers3, href: `/admin/seo-engine/briefs${query}`, description: 'Собираем фразы из Product DNA, компонентов, событий, материала, образа и long-tail.' },
    { title: '3. Метрики', subtitle: 'CSV / API позже', status: 'ожидает', icon: DatabaseZap, href: `/admin/seo-engine/metric-import${query}`, description: 'Экспортируем CSV именно для выбранного товара и возвращаем реальные volume/competition/source/date.' },
    { title: '4. Оценка', subtitle: 'scoring preview', status: 'ожидает', icon: Gauge, href: '/admin/seo-engine/scoring/preview', description: 'После метрик считаем роли: главный, вторичный, supporting, long-tail, hold, reject.' },
    { title: '5. Угол', subtitle: 'уникальность похожих товаров', status: 'готово', icon: Sparkles, href: `/admin/seo-engine/angle-advisor${query}`, description: 'Разводим похожие товары по смыслу: деталь, образ, событие, материал или long-tail.' },
    { title: '6. Черновик', subtitle: 'title / H1 / meta / FAQ / alt', status: 'ожидает', icon: FileText, href: `/admin/seo-engine/draft-preview${query}`, description: 'Собираем будущий SEO-pack по выбранному углу, без сохранения и публикации.' },
    { title: '7. QA', subtitle: 'human / truth / unique', status: 'ожидает', icon: ShieldAlert, href: '/admin/seo-engine/overlap-policy', description: 'Проверяем правду товара, водность, повторы, похожесть, stuffing и ручное утверждение.' },
    { title: '8. Одобрить', subtitle: 'будущая запись', status: 'ожидает', icon: CheckCircle2, href: `/admin/seo-engine/draft-preview${query}`, description: 'Финальный gate перед будущим сохранением в таблицу SEO-черновиков.' },
  ];

  return <main className="min-h-screen bg-[radial-gradient(circle_at_80%_0%,rgba(212,178,106,.13),transparent_32%),linear-gradient(180deg,#07070A,#111016_45%,#07070A)]"><section className="container-feya pt-7 pb-12">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between border-b border-[rgba(216,214,211,.12)] pb-5 mb-5"><div><div className="eyebrow-gold mb-2">Админка · SEO Content Studio</div><h1 className="font-tall text-bone leading-none" style={{ fontSize: 'clamp(34px,5vw,64px)' }}>Единая SEO-воронка</h1><p className="mt-3 max-w-3xl text-[13px] leading-relaxed text-[var(--bone-dim)]">Выбираем товар и ведём его по цепочке: ключи → метрики → оценка → угол → черновик → QA.</p></div><div className="flex flex-wrap gap-2"><Link href={`/admin/seo-engine/metric-import${query}`} className="btn-ghost">Скачать CSV метрик <ArrowUpRight size={13} /></Link><Link href={`/admin/seo-engine/draft-preview${query}`} className="btn-ghost">Черновик <ArrowUpRight size={13} /></Link></div></div>
    {warning || fallbackUsed ? <div className="mb-5 rounded-xl border border-[rgba(212,178,106,.30)] bg-[rgba(212,178,106,.07)] px-3 py-2 text-[12px] text-[var(--bone-dim)]">{warning || 'Включён защитный образец товара.'}</div> : null}
    <div className="mb-5"><Panel title="Выбор товара из каталога" icon={Layers3}><SearchBox q={q} /><div className="mb-3 flex flex-wrap gap-2 text-[11px] text-[var(--bone-dim)]"><span>Загружено товаров: {allCount}</span><span>Показано по фильтру: {products.length}</span>{q ? <span>Поиск: “{q}”</span> : null}</div><ProductGrid products={products} activeKey={activeKey} q={q} /></Panel></div>
    <div className="grid lg:grid-cols-[1fr_340px] gap-5 mb-5"><Panel title="Текущий товар" icon={FileText}><div className="text-bone text-[18px] leading-tight">{brief.productTitle}</div><div className="mt-2 text-[11px] text-[var(--bone-dim)]">ID: {activeKey} · /{brief.productSlug}</div><div className="mt-4 grid sm:grid-cols-2 gap-2">{brief.productFacts.map((fact) => <div key={fact.label} className="rounded-xl border border-[rgba(216,214,211,.10)] bg-black/15 p-2.5"><div className="text-[9px] uppercase tracking-[0.18em] text-[var(--smoke)] mb-1">{fact.label}</div><div className="text-[12px] text-bone leading-snug">{fact.value}</div></div>)}</div></Panel><Panel title="Готовность к ручному прогону" icon={Gauge}><div className="grid grid-cols-2 gap-2"><div className="rounded-xl border border-[rgba(216,214,211,.10)] bg-black/15 p-3"><div className="text-[10px] text-[var(--smoke)]">Фраз на CSV</div><div className="text-bone text-[20px]">{brief.metricValidationPackage.length}</div></div><div className="rounded-xl border border-[rgba(216,214,211,.10)] bg-black/15 p-3"><div className="text-[10px] text-[var(--smoke)]">Ключей в очереди</div><div className="text-bone text-[20px]">{brief.candidateKeywords.length}</div></div></div><div className="mt-3 text-[11px] leading-relaxed text-[var(--bone-dim)]">Следующий шаг: скачать CSV метрик для выбранного товара, заполнить реальные поля и проверить CSV.</div></Panel></div>
    <div className="grid md:grid-cols-2 xl:grid-cols-4 gap-3 mb-5">{steps.map((item) => <Step key={item.title} item={item} />)}</div>
    <div className="grid lg:grid-cols-[.9fr_1.1fr] gap-5 mb-5"><Panel title="Что уже можно делать сейчас" icon={CheckCircle2}><div className="space-y-2 text-[12px] leading-relaxed text-[var(--bone-dim)]"><div>1. Найти и выбрать реальный товар.</div><div>2. Скачать CSV именно для выбранного товара.</div><div>3. Заполнить метрики из Keyword Planner / trusted source.</div><div>4. Проверить CSV и scoring.</div><div>5. Открыть черновик выбранного товара.</div></div></Panel><Panel title="Что ещё блокирует production" icon={ShieldAlert}><div className="grid sm:grid-cols-2 gap-2">{['Нет Google Ads API adapter', 'Нет DataForSEO adapter', 'Нет backend OpenAI generation endpoint', 'Нет persistent humanizer/QA gate', 'Нет save table для SEO drafts', 'Нет approval workflow'].map((item) => <div key={item} className="rounded-xl border border-[rgba(212,178,106,.20)] bg-[rgba(212,178,106,.06)] p-3 text-[11px] text-[var(--bone-dim)]">{item}</div>)}</div></Panel></div>
    <Panel title="Первые фразы для проверки метрик" icon={Layers3}><div className="flex flex-wrap gap-1.5">{brief.metricValidationPackage.map((item) => item.phrase).filter(Boolean).slice(0, 9).map((item) => <span key={item} className="rounded-full border border-[rgba(216,214,211,.10)] bg-black/20 px-2 py-1 text-[10px] text-[var(--bone-dim)]">{item}</span>)}</div></Panel>
  </section></main>;
}
