"""Reproduce the reviewed SQL-only boundary change from captured catalog definitions.
No SQL from a file is sent to a live database. All outputs remain migration artifacts.
"""
import json,re,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
source=json.loads((ROOT/'tests/search-db/fixtures/observed-reader-boundary-20260923.json').read_text())
base=json.loads((ROOT/'tests/search-db/fixtures/observed-metric-schema-20260923.json').read_text())
targets={t['name']:t for t in base['tables'] if t['name'] in ['feya_commerce_seo_keyword_metric_snapshots_v1','feya_commerce_seo_keyword_metric_import_staging_v1']}
views=[r for r in source['dependencies'] if r['definition']]
assert len(views)==14 and len(source['functions'])==3
quote=lambda s:"'"+s.replace("'","''")+"'"
sql=['-- Generated by scripts/build-metric-reader-boundary.py from reviewed catalog snapshots.', '-- No production execution. Prior atomic-import migration is required.','begin;','set local search_path=public;']
manifest=[]
for r in views+source['functions']:
 kind='view' if r in views else 'function'
 identity=r['name'] if kind=='view' else r['identity']
 lookup=('to_regclass' if kind=='view' else 'to_regprocedure')+'('+quote('public.'+identity)+')'
 definition=('pg_get_viewdef' if kind=='view' else 'pg_get_functiondef')+'('+lookup+')'
 md5=hashlib.md5(r['definition'].encode()).hexdigest()
 metadata={'owner':r['owner'],'acl':r['acl'],'options':r['options']}
 meta_sql=("(select jsonb_build_object('owner',pg_get_userbyid(relowner),'acl',relacl::text,'options',reloptions) from pg_class where oid="+lookup+")" if kind=='view' else "(select jsonb_build_object('owner',pg_get_userbyid(proowner),'acl',proacl::text,'options',proconfig) from pg_proc where oid="+lookup+")")
 if kind=='view':
  # PostgreSQL may add implicit UNION target aliases on CREATE VIEW roundtrip.
  # Parse BOTH captured and current definitions identically; do not strip SQL text.
  captured=quote('create temporary view feya_metric_expected_guard as '+r['definition'])
  actual_prefix=quote('create temporary view feya_metric_actual_guard as ')
  sql.append(f"do $guard$ begin execute {captured}; execute {actual_prefix}||{definition}; if pg_get_viewdef('pg_temp.feya_metric_expected_guard'::regclass) is distinct from pg_get_viewdef('pg_temp.feya_metric_actual_guard'::regclass) or {meta_sql} is distinct from {quote(json.dumps(metadata))}::jsonb then raise exception 'Reader definition or privilege drift: {r['name']}'; end if; drop view pg_temp.feya_metric_expected_guard; drop view pg_temp.feya_metric_actual_guard; end $guard$;")
 else:
  sql.append(f"do $guard$ begin if md5({definition}) is distinct from {quote(md5)} or {meta_sql} is distinct from {quote(json.dumps(metadata))}::jsonb then raise exception 'Reader definition or privilege drift: {r['name']}'; end if; end $guard$;")
 manifest.append((kind,identity,definition,meta_sql))

report=[]
for r in views:
 definition=r['definition']; count=0
 for name,t in targets.items():
  columns=', '.join('"'+c['name']+'"' for c in t['columns'])
  pattern=re.compile(r'(\bFROM\s*\(*|\bJOIN\s+)(?:public\.)?'+name+r'\b(?:[ \t]+(?:AS[ \t]+)?([a-z_][a-z_0-9]*))?')
  def replace(m):
   return m.group(1)+'(SELECT '+columns+' FROM public.'+name+' WHERE demand_observation_key IS NULL) AS '+(m.group(2) or name)
  definition,n=pattern.subn(replace,definition);count+=n
 assert count>0,r['name']
 sql.append('create or replace view public.'+r['name']+(' with ('+','.join(r['options'])+')' if r['options'] else '')+' as\n'+definition)
 report.append({'kind':'view','name':r['name'],'filtered_relation_scans':count,'columns':len(r['columns']),'options_preserved':r['options']})
for r in source['functions']:
 definition=r['definition'];count=0
 if r['name']=='feya_fn_apply_manual_keyword_metrics_v1':
  needle='where s.keyword_norm is not null';assert definition.count(needle)==2
  definition=definition.replace(needle,needle+'\n      and s.demand_observation_key is null');count=2
 elif r['name']=='feya_commerce_fn_promote_keyword_metric_import_v1':
  needle='where s.batch_code = p_batch_code';assert definition.count(needle)==4
  definition=definition.replace(needle,needle+'\n    and s.demand_observation_key is null');count=4
  needle='where m.keyword_norm = lower(trim(s.keyword_norm))';assert definition.count(needle)==1
  definition=definition.replace(needle,needle+'\n        and m.demand_observation_key is null');count+=1
 else:
  # This function's only raw reference is an INSERT target; input is the filtered ready view.
  assert r['name']=='feya_commerce_apply_seo_keyword_metric_import_v1'
 if count:sql.append(definition+';')
 report.append({'kind':'function','name':r['name'],'filtered_relation_scans':count,'legacy_input_ready_view':count==0,'security_definer_unchanged':r['security_definer']})

for r,(_,_,_,meta_sql) in zip(views+source['functions'],manifest):
 expected={'owner':r['owner'],'acl':r['acl'],'options':r['options']}
 sql.append(f"do $post$ begin if {meta_sql} is distinct from {quote(json.dumps(expected))}::jsonb then raise exception 'Reader security metadata changed: {r['name']}'; end if; end $post$;")

sql.append('''
create table public.feya_commerce_seo_metric_reader_contracts_v1 (
  object_kind text not null check(object_kind in ('view','function')),
  object_identity text not null,
  definition_md5 text not null,
  metadata_json jsonb not null,
  primary key(object_kind,object_identity)
);
alter table public.feya_commerce_seo_metric_reader_contracts_v1 enable row level security;
revoke all on public.feya_commerce_seo_metric_reader_contracts_v1 from public,anon,authenticated,service_role;
grant select on public.feya_commerce_seo_metric_reader_contracts_v1 to service_role;
''')
for kind,identity,definition,metadata in manifest:
 sql.append('insert into public.feya_commerce_seo_metric_reader_contracts_v1 values('+','.join([quote(kind),quote('public.'+identity),'md5('+definition+')',metadata])+');')
sql.append('''
create function public.feya_commerce_metric_reader_boundary_health_v1() returns text
language plpgsql stable security invoker set search_path='public' as $health$
declare r record; actual_md5 text; actual_metadata jsonb; object_oid oid;
begin
  if (select count(*) from public.feya_commerce_seo_metric_reader_contracts_v1)<>17 then return null; end if;
  if exists (
    select 1 from pg_depend d join pg_rewrite rw on rw.oid=d.objid join pg_class c on c.oid=rw.ev_class join pg_namespace n on n.oid=c.relnamespace
    where d.refclassid='pg_class'::regclass and d.refobjid in ('public.feya_commerce_seo_keyword_metric_snapshots_v1'::regclass,'public.feya_commerce_seo_keyword_metric_import_staging_v1'::regclass)
      and n.nspname='public' and c.relkind in ('v','m')
      and not exists(select 1 from public.feya_commerce_seo_metric_reader_contracts_v1 m where m.object_kind='view' and m.object_identity='public.'||c.relname)
  ) then return null; end if;
  if exists (
    select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace
    where n.nspname='public' and p.prokind='f'
      and (p.prosrc ilike '%feya_commerce_seo_keyword_metric_snapshots_v1%' or p.prosrc ilike '%feya_commerce_seo_keyword_metric_import_staging_v1%')
      and p.oid not in ('public.feya_commerce_import_keyword_metrics_atomic_v1(text,jsonb)'::regprocedure,'public.feya_commerce_metric_reader_boundary_health_v1()'::regprocedure)
      and not exists(select 1 from public.feya_commerce_seo_metric_reader_contracts_v1 m where m.object_kind='function' and to_regprocedure(m.object_identity)=p.oid)
  ) then return null; end if;
  for r in select * from public.feya_commerce_seo_metric_reader_contracts_v1 loop
    if r.object_kind='view' then
      object_oid=to_regclass(r.object_identity);
      actual_md5=md5(pg_get_viewdef(object_oid));
      select jsonb_build_object('owner',pg_get_userbyid(relowner),'acl',relacl::text,'options',reloptions) into actual_metadata from pg_class where oid=object_oid;
    else
      object_oid=to_regprocedure(r.object_identity);
      actual_md5=md5(pg_get_functiondef(object_oid));
      select jsonb_build_object('owner',pg_get_userbyid(proowner),'acl',proacl::text,'options',proconfig) into actual_metadata from pg_proc where oid=object_oid;
    end if;
    if actual_md5 is distinct from r.definition_md5 or actual_metadata is distinct from r.metadata_json then return null; end if;
  end loop;
  return 'metric_reader_boundary_v1';
end $health$;
revoke all on function public.feya_commerce_metric_reader_boundary_health_v1() from public,anon,authenticated;
grant execute on function public.feya_commerce_metric_reader_boundary_health_v1() to service_role;
commit;
''')
(ROOT/'supabase/migrations/20260923234026_keyword_metric_reader_boundary_v1.sql').write_text('\n\n'.join(sql).rstrip()+'\n')
(ROOT/'docs/search/metric-reader-boundary-plan-20260923.json').write_text(json.dumps({'policy':'metric_reader_boundary_v1','strategy':'exclude_atomic_observations_before_legacy_selection','direct_readers':report,'catalog_downstream_views':len([r for r in source['downstream'] if r['relkind']=='v']),'new_metric_approval':False,'production_applied':False},indent=2)+'\n')
print('Prepared',len(report),'readers;',sum(r['filtered_relation_scans'] for r in report),'guarded scans')
