"""Generate an additive access migration from catalog evidence; no DB connection."""
import hashlib,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
f=json.loads((ROOT/'tests/search-db/fixtures/observed-internal-view-closure-20260924.json').read_text())
old=json.loads((ROOT/'tests/search-db/fixtures/observed-metric-closure-20260924.json').read_text())
existing={r['name'] for r in old['relations'] if r['in_metric_closure']}
targets=[r for r in f['relations'] if r['name'] in f['downstream'] and r['name'] not in existing]
assert len(targets)==7 and all(r['kind']=='v' for r in targets)
q=lambda s:"'"+s.replace("'","''")+"'"
manifest='public.feya_commerce_seo_metric_access_contracts_v1'
health='public.feya_commerce_metric_access_boundary_health_v1()'
reader='public.feya_commerce_metric_reader_boundary_health_v1()'
prior=(ROOT/'supabase/migrations/20260924081403_keyword_metric_access_boundary_v1.sql').read_text()
prior_fn=re.search(r'create function public.feya_commerce_metric_access_boundary_health_v1\(\).*?end \$access\$;',prior,re.S).group()
prior_body=prior_fn.split('$access$')[1]
next_fn=prior_fn.replace('create function ','create or replace function ',1).replace('<>50','<>57').replace("return 'metric_access_boundary_v1'", "return 'metric_access_boundary_v2'")
next_fn=next_fn.replace("from "+manifest+" where object_kind='r'\n", "from "+manifest+" where object_kind='r' or object_identity in ("+','.join(q('public.'+n) for n in f['roots'])+")\n")
next_fn=next_fn.replace("d.refclassid='pg_class'::regclass", "d.refclassid='pg_class'::regclass and d.classid='pg_rewrite'::regclass")
helper_checks=[]
for fn in f['functions']:
    body=fn['definition'].split('$function$')[1]
    expected={'owner':fn['owner'],'acl':fn['acl'],'prosecdef':fn['prosecdef'],'proconfig':fn['proconfig'],'body_md5':hashlib.md5(body.encode()).hexdigest()}
    helper_checks.append(f" if (select jsonb_build_object('owner',pg_get_userbyid(proowner),'acl',proacl::text,'prosecdef',prosecdef,'proconfig',proconfig,'body_md5',md5(prosrc)) from pg_proc where oid=to_regprocedure({q('public.'+fn['identity'])})) is distinct from {q(json.dumps(expected))}::jsonb then return null; end if;")
next_fn=next_fn.replace(" return 'metric_access_boundary_v2';",'\n'.join(helper_checks)+"\n return 'metric_access_boundary_v2';")
sql=['-- Generated by scripts/build-internal-view-access.py. UNAPPLIED; no business rows changed.',
     '-- Requires migrations 3–6. Apply with storage OFF; compatible app requires the v2 marker.',
     'begin;','set local search_path=public;',
     f"do $g$ begin if {health} is distinct from 'metric_access_boundary_v1' or {reader} is distinct from 'metric_reader_boundary_v1' then raise exception 'Prior access/reader boundary unhealthy'; end if; if (select count(*) from {manifest})<>50 then raise exception 'Unexpected access manifest version'; end if; if (select md5(prosrc) from pg_proc where oid={q(health)}::regprocedure) is distinct from {q(hashlib.md5(prior_body.encode()).hexdigest())} then raise exception 'Access health definition drift'; end if; end $g$;"]
for r in targets:
    name='public.'+r['name'];expected={k:r[k] for k in ['owner','acl','options','rls']}
    sql.append(f"do $g$ begin if (select jsonb_build_object('owner',pg_get_userbyid(relowner),'acl',relacl::text,'options',reloptions,'rls',relrowsecurity) from pg_class where oid=to_regclass({q(name)})) is distinct from {q(json.dumps(expected))}::jsonb then raise exception 'Internal access preflight drift: {r['name']}'; end if; execute {q('create temporary view feya_internal_expected as '+r['definition'])}; execute 'create temporary view feya_internal_actual as '||pg_get_viewdef({q(name)}::regclass); if pg_get_viewdef('pg_temp.feya_internal_expected'::regclass) is distinct from pg_get_viewdef('pg_temp.feya_internal_actual'::regclass) then raise exception 'Internal view definition drift: {r['name']}'; end if; drop view pg_temp.feya_internal_expected; drop view pg_temp.feya_internal_actual; end $g$;")
    sql.append(f'revoke all on {name} from public,anon,authenticated;')
    sql.append(f"insert into {manifest} select {q(name)},relkind,md5(pg_get_viewdef(oid)),jsonb_build_object('owner',pg_get_userbyid(relowner),'acl',relacl::text,'options',reloptions,'rls',relrowsecurity) from pg_class where oid={q(name)}::regclass;")
sql += [next_fn,f"do $g$ begin if {health} is distinct from 'metric_access_boundary_v2' or {reader} is distinct from 'metric_reader_boundary_v1' then raise exception 'Extended access postcondition failed'; end if; end $g$;",'commit;']
(ROOT/'supabase/migrations/20260924091540_internal_seo_view_access_extension_v1.sql').write_text('\n\n'.join(sql)+'\n')
rollback=['-- Isolated rehearsal / reviewed emergency only. Restores these seven legacy grants.',
          '-- Retains 57-row manifest/v2 health: mismatch closes writes. Keep storage and indexing OFF.',
          'begin;','set local search_path=public;',f"do $g$ begin if {health} is distinct from 'metric_access_boundary_v2' then raise exception 'Rollback preflight drift'; end if; end $g$;"]
for r in targets:
    assert r['acl']=='{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}'
    rollback += [f"revoke all on public.{r['name']} from public,anon,authenticated,service_role;",f"grant all on public.{r['name']} to anon,authenticated,service_role;"]
rollback += [f"do $g$ begin if {health} is not null or {reader} is distinct from 'metric_reader_boundary_v1' then raise exception 'Rollback must close access and preserve reader isolation'; end if; end $g$;",'commit;']
(ROOT/'tests/search-db/fixtures/rollback-internal-view-access.sql').write_text('\n\n'.join(rollback)+'\n')
print('Generated seven-view additive boundary; 57 protected objects; no production connection.')
