"""Generate bounded role revocation from captured live metadata. Never connects to a DB."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
f=json.loads((ROOT/'tests/search-db/fixtures/observed-metric-closure-20260924.json').read_text())
direct=json.loads((ROOT/'tests/search-db/fixtures/observed-reader-boundary-20260923.json').read_text())
direct_names={r['name'] for r in direct['dependencies'] if r['definition']}
targets=[r for r in f['relations'] if r['in_metric_closure']]
assert len(targets)==50 and sum(r['kind']=='v' for r in targets)==48
q=lambda s:"'"+s.replace("'","''")+"'"
health='public.feya_commerce_metric_reader_boundary_health_v1()'
manifest='public.feya_commerce_seo_metric_access_contracts_v1'
access_health='public.feya_commerce_metric_access_boundary_health_v1()'
sql=['-- Generated by scripts/build-metric-access-boundary.py. NOT applied to production.',
     '-- Prerequisites: guarded server-only admin reads + three metric migrations. No business-data mutation.',
     'begin;','set local search_path=public;']
healthy=f"do $g$ begin if {health} is distinct from 'metric_reader_boundary_v1' then raise exception 'Reader contract unhealthy'; end if; end $g$;"
sql.append(healthy)
for r in targets:
    name='public.'+r['name']
    expected={k:r[k] for k in ['owner','acl','options','rls']}
    sql.append(f"do $g$ begin if (select jsonb_build_object('owner',pg_get_userbyid(relowner),'acl',relacl::text,'options',reloptions,'rls',relrowsecurity) from pg_class where oid=to_regclass({q(name)})) is distinct from {q(json.dumps(expected))}::jsonb then raise exception 'Access preflight drift: {r['name']}'; end if; end $g$;")
    if r['kind']=='v' and r['name'] not in direct_names:
        sql.append(f"do $g$ begin execute {q('create temporary view feya_access_expected as '+r['definition'])}; execute 'create temporary view feya_access_actual as '||pg_get_viewdef({q(name)}::regclass); if pg_get_viewdef('pg_temp.feya_access_expected'::regclass) is distinct from pg_get_viewdef('pg_temp.feya_access_actual'::regclass) then raise exception 'Access definition drift: {r['name']}'; end if; drop view pg_temp.feya_access_expected; drop view pg_temp.feya_access_actual; end $g$;")
    sql.append(f'revoke all on {name} from public,anon,authenticated;')

refresh="""do $g$ declare changed integer; begin
update public.feya_commerce_seo_metric_reader_contracts_v1 m set metadata_json=jsonb_build_object('owner',pg_get_userbyid(c.relowner),'acl',c.relacl::text,'options',c.reloptions)
from pg_class c where m.object_kind='view' and c.oid=to_regclass(m.object_identity);
get diagnostics changed=row_count;
if changed<>14 then raise exception 'Unexpected reader manifest size'; end if;
end $g$;"""
sql += [refresh,healthy,f"""create table {manifest}(
 object_identity text primary key, object_kind text not null check(object_kind in ('r','v')),
 definition_md5 text, metadata_json jsonb not null
);
alter table {manifest} enable row level security;
revoke all on {manifest} from public,anon,authenticated,service_role;
grant select on {manifest} to service_role;"""]
for r in targets:
    name='public.'+r['name']
    sql.append(f"insert into {manifest} select {q(name)},relkind,case when relkind='v' then md5(pg_get_viewdef(oid)) end,jsonb_build_object('owner',pg_get_userbyid(relowner),'acl',relacl::text,'options',reloptions,'rls',relrowsecurity) from pg_class where oid={q(name)}::regclass;")
sql.append(f"""create function {access_health} returns text
language plpgsql stable security invoker set search_path=pg_catalog,public,pg_temp as $access$
declare r record; c record; current_oids oid[]; registered_oids oid[];
begin
 if (select count(*) from {manifest})<>50 or (select count(*) from {manifest} where object_kind='r')<>2 then return null; end if;
 with recursive closure(oid) as (
  select to_regclass(object_identity)::oid from {manifest} where object_kind='r'
  union select rw.ev_class from closure t join pg_depend d on d.refobjid=t.oid and d.refclassid='pg_class'::regclass
  join pg_rewrite rw on rw.oid=d.objid join pg_class v on v.oid=rw.ev_class where v.relkind in ('v','m') and v.oid<>t.oid
 ) select array_agg(oid order by oid) into current_oids from closure;
 select array_agg(to_regclass(object_identity)::oid order by to_regclass(object_identity)::oid) into registered_oids from {manifest};
 if current_oids is distinct from registered_oids then return null; end if;
 for r in select * from {manifest} loop
  select * into c from pg_class where oid=to_regclass(r.object_identity);
  if not found or c.relkind::text<>r.object_kind then return null; end if;
  if has_table_privilege('anon',c.oid,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER')
   or has_table_privilege('authenticated',c.oid,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER')
   or not has_table_privilege('service_role',c.oid,'SELECT') then return null; end if;
  if jsonb_build_object('owner',pg_get_userbyid(c.relowner),'acl',c.relacl::text,'options',c.reloptions,'rls',c.relrowsecurity) is distinct from r.metadata_json then return null; end if;
  if r.object_kind='v' and md5(pg_get_viewdef(c.oid)) is distinct from r.definition_md5 then return null; end if;
 end loop;
 return 'metric_access_boundary_v1';
end $access$;
revoke all on function {access_health} from public,anon,authenticated;
grant execute on function {access_health} to service_role;
do $g$ begin if {access_health} is distinct from 'metric_access_boundary_v1' then raise exception 'Access postcondition failed'; end if; end $g$;
{healthy}
commit;""")
(ROOT/'supabase/migrations/20260924081403_keyword_metric_access_boundary_v1.sql').write_text('\n\n'.join(sql)+'\n')
rollback=['-- Isolated rehearsal / reviewed emergency only. Restores legacy exposure; keep application writes and indexing OFF.',
          '-- Retains access manifest/health: access health becomes NULL, so the new write gate stays closed.',
          'begin;','set local search_path=public;',healthy,
          f"do $g$ begin if {access_health} is distinct from 'metric_access_boundary_v1' then raise exception 'Rollback preflight drift'; end if; end $g$;"]
for r in targets:
    assert r['acl']=='{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}'
    name='public.'+r['name']
    rollback += [f'revoke all on {name} from public,anon,authenticated,service_role;',f'grant all on {name} to anon,authenticated,service_role;']
rollback += [refresh,healthy,f"do $g$ begin if {access_health} is not null then raise exception 'Rollback must leave access gate closed'; end if; end $g$;",'commit;']
(ROOT/'tests/search-db/fixtures/rollback-metric-access-boundary.sql').write_text('\n\n'.join(rollback)+'\n')
print('Generated 50-object access boundary and guarded rollback; production untouched.')
