"""Generate a bounded search_path migration and its isolated rollback rehearsal.
No connection to Supabase; all business SQL, ACLs and IDs are preserved.
"""
import hashlib, json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
source = json.loads((ROOT / 'tests/search-db/fixtures/observed-metric-security-20260924.json').read_text())
quote = lambda s: "'" + s.replace("'", "''") + "'"
functions = source['functions']
assert len(functions) == 4
fixed = ['search_path=pg_catalog, pg_temp']
manifest = 'public.feya_commerce_seo_metric_reader_contracts_v1'
health = 'public.feya_commerce_metric_reader_boundary_health_v1()'

def body_hash(fn):
    body = fn['definition'].split('AS $function$')[1].split('$function$')[0]
    if fn['identity'].startswith('feya_fn_apply_manual_keyword_metrics_v1('):
        assert body.count('where s.keyword_norm is not null') == 2
        body = body.replace('where s.keyword_norm is not null', 'where s.keyword_norm is not null\n      and s.demand_observation_key is null')
    if fn['identity'].startswith('feya_commerce_fn_promote_keyword_metric_import_v1('):
        assert body.count('where s.batch_code = p_batch_code') == 4
        body = body.replace('where s.batch_code = p_batch_code', 'where s.batch_code = p_batch_code\n    and s.demand_observation_key is null')
        body = body.replace('where m.keyword_norm = lower(trim(s.keyword_norm))', 'where m.keyword_norm = lower(trim(s.keyword_norm))\n        and m.demand_observation_key is null')
    return hashlib.md5(body.encode()).hexdigest()

def guard(fn, options):
    expected = {k: fn[k] for k in ['owner', 'acl', 'security_definer']}
    expected.update(options=options, body_md5=body_hash(fn))
    return f"""do $guard$ begin
  if (select jsonb_build_object('owner',pg_get_userbyid(proowner),'acl',proacl::text,
    'security_definer',prosecdef,'options',proconfig,'body_md5',md5(prosrc))
    from pg_proc where oid=to_regprocedure({quote('public.'+fn['identity'])}))
    is distinct from {quote(json.dumps(expected))}::jsonb
  then raise exception 'Function hardening preflight drift: {fn['identity']}'; end if;
end $guard$;"""

health_guard = f"do $health$ begin if {health} is distinct from 'metric_reader_boundary_v1' then raise exception 'Reader contract unhealthy; no function settings changed'; end if; end $health$;"
identities = ','.join(quote('public.'+fn['identity']) for fn in functions if fn['security_definer'])
refresh = f"""-- Rebaseline ONLY the three reviewed function settings; retain all 14 view contracts.
do $refresh$ declare changed integer; begin
  update {manifest} m set
    definition_md5=md5(pg_get_functiondef(p.oid)),
    metadata_json=jsonb_build_object('owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'options',p.proconfig)
  from pg_proc p where m.object_kind='function' and m.object_identity in ({identities})
    and p.oid=to_regprocedure(m.object_identity);
  get diagnostics changed = row_count;
  if changed<>3 then raise exception 'Unexpected reader manifest update count'; end if;
end $refresh$;"""

for rollback in [False, True]:
    sql = ['-- Generated by scripts/build-metric-function-hardening.py. NOT applied to production.',
           '-- Requires atomic-import + reader-boundary migrations. No ACL, RLS, body or business-data change.',
           '-- Rollback is an isolated rehearsal/emergency artifact, not an automatic down migration.' if rollback else '-- Fixed trusted path; every business relation in these four bodies is schema-qualified.',
           'begin;', "set local search_path=pg_catalog,pg_temp;", health_guard]
    sql += [guard(fn, fixed if rollback else fn['options']) for fn in functions]
    for fn in functions:
        setting = "reset search_path" if rollback and fn['options'] is None else "set search_path to public" if rollback else "set search_path to pg_catalog, pg_temp"
        sql.append(f"alter function public.{fn['identity']} {setting};")
    sql += [guard(fn, fn['options'] if rollback else fixed) for fn in functions]
    sql += [refresh, health_guard, 'commit;']
    destination = 'tests/search-db/fixtures/rollback-metric-function-hardening.sql' if rollback else 'supabase/migrations/20260924005636_keyword_metric_function_search_path_v1.sql'
    (ROOT / destination).write_text('\n\n'.join(sql)+'\n')
print('Generated four-function hardening and guarded rollback; production untouched.')
