with recursive roots(name) as (values ('feya_commerce_product_drafts'),('feya_commerce_seo_pages_v1'),('feya_growth_execution_requests_v1'),('feya_growth_change_events_v1'),('feya_commerce_seo_pack_drafts_v1'),('feya_commerce_seo_pack_draft_events_v1')), deps(oid) as (
 select c.oid from pg_class c join pg_namespace n on n.oid=c.relnamespace join roots r on r.name=c.relname where n.nspname='public'
 union select con.confrelid from pg_constraint con join deps d on con.conrelid=d.oid where con.contype='f'
), rels as (select c.*,n.nspname from deps d join pg_class c on c.oid=d.oid join pg_namespace n on n.oid=c.relnamespace)
select jsonb_build_object(
'observed_at',current_timestamp,'server_version',current_setting('server_version'),'scope','14-table FK dependency closure; schema only; no customer/auth rows',
'tables',(select jsonb_agg(jsonb_build_object('schema',r.nspname,'name',r.relname,'rls',r.relrowsecurity,'force_rls',r.relforcerowsecurity,'owner',pg_get_userbyid(r.relowner),
'columns',(select jsonb_agg(jsonb_build_object('name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'not_null',a.attnotnull,'default',pg_get_expr(d.adbin,d.adrelid),'generated',a.attgenerated,'identity',a.attidentity) order by a.attnum) from pg_attribute a left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where a.attrelid=r.oid and a.attnum>0 and not a.attisdropped),
'constraints',(select coalesce(jsonb_agg(jsonb_build_object('name',conname,'type',contype,'definition',pg_get_constraintdef(oid)) order by conname),'[]'::jsonb) from pg_constraint where conrelid=r.oid),
'indexes',(select coalesce(jsonb_agg(pg_get_indexdef(indexrelid) order by indexrelid),'[]'::jsonb) from pg_index where indrelid=r.oid and not exists(select 1 from pg_constraint where conindid=indexrelid)),
'triggers',(select coalesce(jsonb_agg(jsonb_build_object('name',tgname,'definition',pg_get_triggerdef(oid)) order by tgname),'[]'::jsonb) from pg_trigger where tgrelid=r.oid and not tgisinternal),
'policies',(select coalesce(jsonb_agg(to_jsonb(p)),'[]'::jsonb) from pg_policies p where p.schemaname=r.nspname and p.tablename=r.relname),
'grants',(select coalesce(jsonb_agg(jsonb_build_object('grantee',case when x.grantee=0 then 'PUBLIC' else pg_get_userbyid(x.grantee) end,'privilege',x.privilege_type,'grantable',x.is_grantable)),'[]'::jsonb) from aclexplode(coalesce(r.relacl,acldefault('r',r.relowner))) x)
) order by r.nspname,r.relname) from rels r),
'supporting_functions',(select jsonb_agg(jsonb_build_object('definition',pg_get_functiondef(p.oid))) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='feya_fn_execution_request_material_json_v1'),
 'trigger_functions',(select coalesce(jsonb_agg(jsonb_build_object('schema',n.nspname,'name',p.proname,'definition',pg_get_functiondef(p.oid)) order by p.proname),'[]'::jsonb) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where p.oid in(select t.tgfoid from pg_trigger t join deps d on d.oid=t.tgrelid where not t.tgisinternal)),
'views',(select jsonb_agg(jsonb_build_object('schema',n.nspname,'name',c.relname,'definition',pg_get_viewdef(c.oid,true),'options',c.reloptions,'grants',(select jsonb_agg(jsonb_build_object('grantee',case when x.grantee=0 then 'PUBLIC' else pg_get_userbyid(x.grantee) end,'privilege',x.privilege_type)) from aclexplode(coalesce(c.relacl,acldefault('r',c.relowner))) x)) order by c.relname) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ('feya_commerce_v_seo_pack_drafts_latest_v1','feya_commerce_v_seo_pack_review_queue_v1')),
'default_acls',(select jsonb_agg(jsonb_build_object('owner',pg_get_userbyid(d.defaclrole),'schema',n.nspname,'object_type',d.defaclobjtype,'grants',(select jsonb_agg(jsonb_build_object('grantee',case when x.grantee=0 then 'PUBLIC' else pg_get_userbyid(x.grantee) end,'privilege',x.privilege_type)) from aclexplode(d.defaclacl) x))) from pg_default_acl d left join pg_namespace n on n.oid=d.defaclnamespace where n.nspname='public' or d.defaclnamespace=0)
) as snapshot;
