-- Generated by scripts/build-internal-view-access.py. UNAPPLIED; no business rows changed.

-- Requires migrations 3–6. Apply with storage OFF; compatible app requires the v2 marker.

begin;

set local search_path=public;

do $g$ begin if public.feya_commerce_metric_access_boundary_health_v1() is distinct from 'metric_access_boundary_v1' or public.feya_commerce_metric_reader_boundary_health_v1() is distinct from 'metric_reader_boundary_v1' then raise exception 'Prior access/reader boundary unhealthy'; end if; if (select count(*) from public.feya_commerce_seo_metric_access_contracts_v1)<>50 then raise exception 'Unexpected access manifest version'; end if; if (select md5(prosrc) from pg_proc where oid='public.feya_commerce_metric_access_boundary_health_v1()'::regprocedure) is distinct from '993a06ac32d93ef49b8c04881bb20081' then raise exception 'Access health definition drift'; end if; end $g$;

do $g$ begin if (select jsonb_build_object('owner',pg_get_userbyid(relowner),'acl',relacl::text,'options',reloptions,'rls',relrowsecurity) from pg_class where oid=to_regclass('public.feya_commerce_v_keyword_cleanup_review_risk_v1')) is distinct from '{"owner": "postgres", "acl": "{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}", "options": ["security_barrier=true"], "rls": false}'::jsonb then raise exception 'Internal access preflight drift: feya_commerce_v_keyword_cleanup_review_risk_v1'; end if; execute 'create temporary view feya_internal_expected as  WITH latest AS (
         SELECT c.cleanup_id,
            c.run_id,
            c.keyword_id,
            c.keyword_norm,
            c.original_keyword,
            c.cleaned_keyword,
            c.suggested_keyword,
            c.keyword_axis,
            c.keyword_pattern,
            c.suggested_page_level,
            c.ai_intent,
            c.ai_rewrite_status,
            c.should_validate_api,
            c.should_use_for_product,
            c.should_use_for_collection,
            c.should_use_for_image_alt,
            c.should_hold,
            c.warning_flags,
            c.ai_reason,
            c.model_name,
            c.prompt_version,
            c.source_queue_snapshot,
            c.raw_ai_response_json,
            c.review_status,
            c.approved_keyword,
            c.approved_keyword_norm,
            c.approved_at,
            c.approved_by,
            c.created_at,
            c.updated_at,
            row_number() OVER (PARTITION BY c.keyword_norm ORDER BY c.created_at DESC, c.cleanup_id DESC) AS rn
           FROM feya_commerce_seo_keyword_ai_cleanup_v1 c
          WHERE (c.review_status = ''pending''::text)
        ), prepared AS (
         SELECT l.cleanup_id,
            l.run_id,
            l.keyword_id,
            l.keyword_norm,
            l.original_keyword,
            l.cleaned_keyword,
            l.suggested_keyword,
            l.keyword_axis,
            l.keyword_pattern,
            l.suggested_page_level,
            l.ai_intent,
            l.ai_rewrite_status,
            l.should_validate_api,
            l.should_use_for_product,
            l.should_use_for_collection,
            l.should_use_for_image_alt,
            l.should_hold,
            l.warning_flags,
            l.ai_reason,
            l.model_name,
            l.prompt_version,
            l.source_queue_snapshot,
            l.raw_ai_response_json,
            l.review_status,
            l.approved_keyword,
            l.approved_keyword_norm,
            l.approved_at,
            l.approved_by,
            l.created_at,
            l.updated_at,
            l.rn,
            COALESCE(NULLIF(btrim(l.suggested_keyword), ''''::text), NULLIF(btrim(l.cleaned_keyword), ''''::text), NULLIF(btrim(l.original_keyword), ''''::text)) AS effective_keyword,
            regexp_replace(lower(btrim(l.original_keyword)), ''\s+''::text, '' ''::text, ''g''::text) AS normalized_original,
            ((
                CASE
                    WHEN l.should_use_for_product THEN 1
                    ELSE 0
                END +
                CASE
                    WHEN l.should_use_for_collection THEN 1
                    ELSE 0
                END) +
                CASE
                    WHEN l.should_use_for_image_alt THEN 1
                    ELSE 0
                END) AS use_lane_count,
            (EXISTS ( SELECT 1
                   FROM jsonb_array_elements_text(l.warning_flags) w(flag)
                  WHERE (w.flag <> ALL (ARRAY[''deterministic_cleanup_without_openai''::text, ''auto_filled_suggested_keyword_from_cleaned''::text, ''auto_normalized_unchanged_status''::text, ''auto_repaired_batch50_schema_drift''::text])))) AS has_nontechnical_warning,
            (l.warning_flags ? ''auto_repaired_batch50_schema_drift''::text) AS schema_drift_repair
           FROM latest l
          WHERE (l.rn = 1)
        )
 SELECT cleanup_id,
    keyword_id,
    keyword_norm,
    original_keyword,
    cleaned_keyword,
    suggested_keyword,
    effective_keyword,
    keyword_axis,
    keyword_pattern,
    suggested_page_level,
    ai_intent,
    ai_rewrite_status,
    should_validate_api,
    should_use_for_product,
    should_use_for_collection,
    should_use_for_image_alt,
    should_hold,
    warning_flags,
    ai_reason,
    model_name,
    prompt_version,
    created_at,
    (lower(effective_keyword) = normalized_original) AS normalization_only,
    use_lane_count,
        CASE
            WHEN should_hold THEN ''HIGH''::text
            WHEN (effective_keyword IS NULL) THEN ''HIGH''::text
            WHEN ((ai_intent IS NULL) OR (ai_intent = ''unclear''::text)) THEN ''HIGH''::text
            WHEN (use_lane_count <> 1) THEN ''HIGH''::text
            WHEN (suggested_page_level = ''image_alt''::text) THEN ''HIGH''::text
            WHEN schema_drift_repair THEN ''HIGH''::text
            WHEN has_nontechnical_warning THEN ''HIGH''::text
            WHEN (lower(effective_keyword) <> normalized_original) THEN ''HIGH''::text
            WHEN (suggested_page_level = ''collection''::text) THEN ''MEDIUM''::text
            WHEN ((suggested_page_level = ''product''::text) AND (ai_intent = ANY (ARRAY[''transactional''::text, ''commercial''::text]))) THEN ''LOW''::text
            ELSE ''MEDIUM''::text
        END AS review_risk,
        CASE
            WHEN should_hold THEN ''HOLD_REVIEW''::text
            WHEN (effective_keyword IS NULL) THEN ''SEMANTIC_DEEP_REVIEW''::text
            WHEN ((ai_intent IS NULL) OR (ai_intent = ''unclear''::text)) THEN ''SEMANTIC_DEEP_REVIEW''::text
            WHEN (use_lane_count <> 1) THEN ''ROUTING_CONFLICT_REVIEW''::text
            WHEN (suggested_page_level = ''image_alt''::text) THEN ''IMAGE_ALT_REVIEW''::text
            WHEN schema_drift_repair THEN ''SCHEMA_REPAIR_REVIEW''::text
            WHEN has_nontechnical_warning THEN ''WARNING_REVIEW''::text
            WHEN (lower(effective_keyword) <> normalized_original) THEN ''SEMANTIC_REWRITE_REVIEW''::text
            WHEN (suggested_page_level = ''collection''::text) THEN ''COLLECTION_ROUTING_REVIEW''::text
            ELSE ''FAST_SEMANTIC_REVIEW''::text
        END AS review_lane
   FROM prepared p;'; execute 'create temporary view feya_internal_actual as '||pg_get_viewdef('public.feya_commerce_v_keyword_cleanup_review_risk_v1'::regclass); if pg_get_viewdef('pg_temp.feya_internal_expected'::regclass) is distinct from pg_get_viewdef('pg_temp.feya_internal_actual'::regclass) then raise exception 'Internal view definition drift: feya_commerce_v_keyword_cleanup_review_risk_v1'; end if; drop view pg_temp.feya_internal_expected; drop view pg_temp.feya_internal_actual; end $g$;

revoke all on public.feya_commerce_v_keyword_cleanup_review_risk_v1 from public,anon,authenticated;

insert into public.feya_commerce_seo_metric_access_contracts_v1 select 'public.feya_commerce_v_keyword_cleanup_review_risk_v1',relkind,md5(pg_get_viewdef(oid)),jsonb_build_object('owner',pg_get_userbyid(relowner),'acl',relacl::text,'options',reloptions,'rls',relrowsecurity) from pg_class where oid='public.feya_commerce_v_keyword_cleanup_review_risk_v1'::regclass;

do $g$ begin if (select jsonb_build_object('owner',pg_get_userbyid(relowner),'acl',relacl::text,'options',reloptions,'rls',relrowsecurity) from pg_class where oid=to_regclass('public.feya_commerce_v_keyword_cleanup_review_status_safe_v1')) is distinct from '{"owner": "postgres", "acl": "{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}", "options": ["security_barrier=true"], "rls": false}'::jsonb then raise exception 'Internal access preflight drift: feya_commerce_v_keyword_cleanup_review_status_safe_v1'; end if; execute 'create temporary view feya_internal_expected as  WITH latest_rec AS (
         SELECT DISTINCT ON (r.cleanup_id) r.cleanup_id,
            r.recommendation_id,
            r.review_risk,
            r.recommendation,
            r.recommended_keyword,
            r.recommended_page_level,
            r.recommended_intent,
            r.issues_json,
            r.reason,
            r.model_name,
            r.prompt_version,
            r.created_at AS recommendation_created_at
           FROM feya_commerce_seo_keyword_cleanup_review_recommendations_v1 r
          ORDER BY r.cleanup_id, r.created_at DESC, r.recommendation_id DESC
        )
 SELECT q.cleanup_id,
    q.keyword_id,
    q.keyword_norm,
    q.original_keyword,
    q.cleaned_keyword,
    q.suggested_keyword,
    q.effective_keyword,
    q.keyword_axis,
    q.keyword_pattern,
    q.suggested_page_level,
    q.ai_intent,
    q.warning_flags,
    q.normalization_only,
    q.review_risk,
    q.review_lane,
    c.review_status,
    c.approved_keyword,
    c.approved_at,
    lr.recommendation_id,
    lr.recommendation,
    lr.recommended_keyword,
    lr.recommended_page_level,
    lr.recommended_intent,
    lr.issues_json,
    lr.reason AS recommendation_reason,
    lr.model_name AS review_model_name,
    lr.prompt_version AS review_prompt_version,
    lr.recommendation_created_at
   FROM ((feya_commerce_v_keyword_cleanup_review_risk_v1 q
     JOIN feya_commerce_seo_keyword_ai_cleanup_v1 c ON ((c.cleanup_id = q.cleanup_id)))
     LEFT JOIN latest_rec lr ON ((lr.cleanup_id = q.cleanup_id)));'; execute 'create temporary view feya_internal_actual as '||pg_get_viewdef('public.feya_commerce_v_keyword_cleanup_review_status_safe_v1'::regclass); if pg_get_viewdef('pg_temp.feya_internal_expected'::regclass) is distinct from pg_get_viewdef('pg_temp.feya_internal_actual'::regclass) then raise exception 'Internal view definition drift: feya_commerce_v_keyword_cleanup_review_status_safe_v1'; end if; drop view pg_temp.feya_internal_expected; drop view pg_temp.feya_internal_actual; end $g$;

revoke all on public.feya_commerce_v_keyword_cleanup_review_status_safe_v1 from public,anon,authenticated;

insert into public.feya_commerce_seo_metric_access_contracts_v1 select 'public.feya_commerce_v_keyword_cleanup_review_status_safe_v1',relkind,md5(pg_get_viewdef(oid)),jsonb_build_object('owner',pg_get_userbyid(relowner),'acl',relacl::text,'options',reloptions,'rls',relrowsecurity) from pg_class where oid='public.feya_commerce_v_keyword_cleanup_review_status_safe_v1'::regclass;

do $g$ begin if (select jsonb_build_object('owner',pg_get_userbyid(relowner),'acl',relacl::text,'options',reloptions,'rls',relrowsecurity) from pg_class where oid=to_regclass('public.feya_commerce_v_page_ownership_shortlist_v1')) is distinct from '{"owner": "postgres", "acl": "{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}", "options": ["security_barrier=true"], "rls": false}'::jsonb then raise exception 'Internal access preflight drift: feya_commerce_v_page_ownership_shortlist_v1'; end if; execute 'create temporary view feya_internal_expected as  WITH cluster_text AS (
         SELECT c.query_cluster_id,
            c.cluster_code,
            c.cluster_label,
            c.normalized_intent,
            c.intent_type,
            c.language_code,
            c.market_scope,
            feya_fn_content_token_set_v1(((c.normalized_intent || '' ''::text) || COALESCE(( SELECT string_agg(m.keyword_norm, '' ''::text) AS string_agg
                   FROM feya_commerce_seo_query_cluster_members_v1 m
                  WHERE ((m.query_cluster_id = c.query_cluster_id) AND (m.member_role <> ''excluded''::text))), ''''::text))) AS cluster_tokens
           FROM feya_commerce_v_page_query_ownership_candidate_clusters_v1 c
          WHERE (c.ownership_candidate_status = ''READY_FOR_OWNERSHIP_PROPOSAL''::text)
        ), page_text AS (
         SELECT p.seo_page_id,
            p.page_type,
            p.canonical_product_id,
            p.url_path,
            p.market_code,
            p.locale,
            p.lifecycle_state,
            p.indexation_intent,
            p.protected_winner_flag,
            pd.card_title,
            pd.h1,
            pd.product_type,
            pd.material,
            pd.color,
            feya_fn_content_token_set_v1(((((((((COALESCE(pd.card_title, ''''::text) || '' ''::text) || COALESCE(pd.h1, ''''::text)) || '' ''::text) || COALESCE(pd.product_type, ''''::text)) || '' ''::text) || COALESCE(pd.material, ''''::text)) || '' ''::text) || COALESCE(pd.color, ''''::text))) AS page_tokens
           FROM (feya_commerce_seo_pages_v1 p
             LEFT JOIN feya_commerce_product_drafts pd ON ((pd.canonical_product_id = p.canonical_product_id)))
          WHERE ((p.portfolio_status = ''active''::text) AND (p.indexation_intent = ANY (ARRAY[''candidate''::text, ''indexable''::text])))
        ), scored AS (
         SELECT c.query_cluster_id,
            c.cluster_code,
            c.cluster_label,
            c.normalized_intent,
            c.intent_type,
            p.seo_page_id,
            p.page_type,
            p.canonical_product_id,
            p.url_path,
            p.market_code,
            p.locale,
            p.lifecycle_state,
            p.indexation_intent,
            p.protected_winner_flag,
            p.card_title,
            p.h1,
            p.product_type,
            p.material,
            p.color,
            feya_fn_content_jaccard_v1(c.cluster_tokens, p.page_tokens) AS lexical_overlap_score
           FROM (cluster_text c
             CROSS JOIN page_text p)
          WHERE ((p.market_code = ''US''::text) AND (p.locale = ''en-US''::text))
        ), ranked AS (
         SELECT s.query_cluster_id,
            s.cluster_code,
            s.cluster_label,
            s.normalized_intent,
            s.intent_type,
            s.seo_page_id,
            s.page_type,
            s.canonical_product_id,
            s.url_path,
            s.market_code,
            s.locale,
            s.lifecycle_state,
            s.indexation_intent,
            s.protected_winner_flag,
            s.card_title,
            s.h1,
            s.product_type,
            s.material,
            s.color,
            s.lexical_overlap_score,
            row_number() OVER (PARTITION BY s.query_cluster_id ORDER BY s.lexical_overlap_score DESC, s.url_path) AS shortlist_rank
           FROM scored s
          WHERE (s.lexical_overlap_score > (0)::numeric)
        )
 SELECT query_cluster_id,
    cluster_code,
    cluster_label,
    normalized_intent,
    intent_type,
    seo_page_id,
    page_type,
    canonical_product_id,
    url_path,
    market_code,
    locale,
    lifecycle_state,
    indexation_intent,
    protected_winner_flag,
    card_title,
    h1,
    product_type,
    material,
    color,
    lexical_overlap_score,
    shortlist_rank,
    ''lexical_candidate_retrieval_not_ownership''::text AS shortlist_method
   FROM ranked r
  WHERE (shortlist_rank <= 20);'; execute 'create temporary view feya_internal_actual as '||pg_get_viewdef('public.feya_commerce_v_page_ownership_shortlist_v1'::regclass); if pg_get_viewdef('pg_temp.feya_internal_expected'::regclass) is distinct from pg_get_viewdef('pg_temp.feya_internal_actual'::regclass) then raise exception 'Internal view definition drift: feya_commerce_v_page_ownership_shortlist_v1'; end if; drop view pg_temp.feya_internal_expected; drop view pg_temp.feya_internal_actual; end $g$;

revoke all on public.feya_commerce_v_page_ownership_shortlist_v1 from public,anon,authenticated;

insert into public.feya_commerce_seo_metric_access_contracts_v1 select 'public.feya_commerce_v_page_ownership_shortlist_v1',relkind,md5(pg_get_viewdef(oid)),jsonb_build_object('owner',pg_get_userbyid(relowner),'acl',relacl::text,'options',reloptions,'rls',relrowsecurity) from pg_class where oid='public.feya_commerce_v_page_ownership_shortlist_v1'::regclass;

do $g$ begin if (select jsonb_build_object('owner',pg_get_userbyid(relowner),'acl',relacl::text,'options',reloptions,'rls',relrowsecurity) from pg_class where oid=to_regclass('public.feya_commerce_v_page_query_ownership_candidate_clusters_v1')) is distinct from '{"owner": "postgres", "acl": "{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}", "options": ["security_barrier=true"], "rls": false}'::jsonb then raise exception 'Internal access preflight drift: feya_commerce_v_page_query_ownership_candidate_clusters_v1'; end if; execute 'create temporary view feya_internal_expected as  WITH primary_owner AS (
         SELECT o.query_cluster_id,
            (count(*))::integer AS primary_owner_count
           FROM feya_commerce_seo_page_query_ownership_v1 o
          WHERE ((o.ownership_role = ''primary''::text) AND (o.ownership_status = ANY (ARRAY[''intended''::text, ''active''::text, ''protected''::text])) AND (o.effective_to IS NULL))
          GROUP BY o.query_cluster_id
        )
 SELECT c.query_cluster_id,
    c.cluster_code,
    c.cluster_label,
    c.normalized_intent,
    c.intent_type,
    c.language_code,
    c.market_scope,
    c.cluster_status,
    (count(m.query_cluster_member_id))::integer AS member_count,
    COALESCE(po.primary_owner_count, 0) AS primary_owner_count,
        CASE
            WHEN (c.cluster_status <> ''approved''::text) THEN ''NOT_READY''::text
            WHEN (COALESCE(po.primary_owner_count, 0) > 0) THEN ''OWNERSHIP_EXISTS''::text
            ELSE ''READY_FOR_OWNERSHIP_PROPOSAL''::text
        END AS ownership_candidate_status
   FROM ((feya_commerce_seo_query_clusters_v1 c
     LEFT JOIN feya_commerce_seo_query_cluster_members_v1 m ON (((m.query_cluster_id = c.query_cluster_id) AND (m.member_role <> ''excluded''::text))))
     LEFT JOIN primary_owner po ON ((po.query_cluster_id = c.query_cluster_id)))
  GROUP BY c.query_cluster_id, c.cluster_code, c.cluster_label, c.normalized_intent, c.intent_type, c.language_code, c.market_scope, c.cluster_status, po.primary_owner_count;'; execute 'create temporary view feya_internal_actual as '||pg_get_viewdef('public.feya_commerce_v_page_query_ownership_candidate_clusters_v1'::regclass); if pg_get_viewdef('pg_temp.feya_internal_expected'::regclass) is distinct from pg_get_viewdef('pg_temp.feya_internal_actual'::regclass) then raise exception 'Internal view definition drift: feya_commerce_v_page_query_ownership_candidate_clusters_v1'; end if; drop view pg_temp.feya_internal_expected; drop view pg_temp.feya_internal_actual; end $g$;

revoke all on public.feya_commerce_v_page_query_ownership_candidate_clusters_v1 from public,anon,authenticated;

insert into public.feya_commerce_seo_metric_access_contracts_v1 select 'public.feya_commerce_v_page_query_ownership_candidate_clusters_v1',relkind,md5(pg_get_viewdef(oid)),jsonb_build_object('owner',pg_get_userbyid(relowner),'acl',relacl::text,'options',reloptions,'rls',relrowsecurity) from pg_class where oid='public.feya_commerce_v_page_query_ownership_candidate_clusters_v1'::regclass;

do $g$ begin if (select jsonb_build_object('owner',pg_get_userbyid(relowner),'acl',relacl::text,'options',reloptions,'rls',relrowsecurity) from pg_class where oid=to_regclass('public.feya_commerce_v_seo_api_validation_queue_v1')) is distinct from '{"owner": "postgres", "acl": "{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}", "options": null, "rls": false}'::jsonb then raise exception 'Internal access preflight drift: feya_commerce_v_seo_api_validation_queue_v1'; end if; execute 'create temporary view feya_internal_expected as  SELECT keyword_id,
    keyword,
    keyword_norm,
    keyword_word_count,
    keyword_axis,
    keyword_pattern,
    product_count,
    suggested_page_level,
    priority_tier,
    validation_priority,
    validation_status,
    requires_api_validation,
    reason,
    source,
    first_seen_at,
    last_seen_at
   FROM feya_commerce_seo_keyword_master_v1 m
  WHERE ((active_flag IS TRUE) AND (validation_status = ''queued''::text) AND (requires_api_validation IS TRUE) AND (keyword_word_count >= 2) AND (validation_priority <> ''low''::text) AND (COALESCE(reason, ''''::text) !~~* ''%size phrase%''::text) AND (COALESCE(reason, ''''::text) !~~* ''%bundle option%''::text) AND (keyword_norm <> ALL (ARRAY[''full set''::text, ''whole product''::text, ''choose your set''::text, ''полный комплект''::text])) AND (keyword_norm !~ ''(^|[^a-z0-9])(xxs|xs|s us|m us|l us|xl|2x|3x|size|размер|буквенный)([^a-z0-9]|$)''::text) AND (NOT (EXISTS ( SELECT 1
           FROM feya_commerce_seo_keyword_compatibility_block_rules_v1 r
          WHERE ((r.active_flag IS TRUE) AND (m.keyword_norm ~ r.block_regex) AND ((r.allowed_regex IS NULL) OR (m.keyword_norm !~ r.allowed_regex)))))));'; execute 'create temporary view feya_internal_actual as '||pg_get_viewdef('public.feya_commerce_v_seo_api_validation_queue_v1'::regclass); if pg_get_viewdef('pg_temp.feya_internal_expected'::regclass) is distinct from pg_get_viewdef('pg_temp.feya_internal_actual'::regclass) then raise exception 'Internal view definition drift: feya_commerce_v_seo_api_validation_queue_v1'; end if; drop view pg_temp.feya_internal_expected; drop view pg_temp.feya_internal_actual; end $g$;

revoke all on public.feya_commerce_v_seo_api_validation_queue_v1 from public,anon,authenticated;

insert into public.feya_commerce_seo_metric_access_contracts_v1 select 'public.feya_commerce_v_seo_api_validation_queue_v1',relkind,md5(pg_get_viewdef(oid)),jsonb_build_object('owner',pg_get_userbyid(relowner),'acl',relacl::text,'options',reloptions,'rls',relrowsecurity) from pg_class where oid='public.feya_commerce_v_seo_api_validation_queue_v1'::regclass;

do $g$ begin if (select jsonb_build_object('owner',pg_get_userbyid(relowner),'acl',relacl::text,'options',reloptions,'rls',relrowsecurity) from pg_class where oid=to_regclass('public.feya_commerce_v_seo_keyword_ai_cleanup_report_v1')) is distinct from '{"owner": "postgres", "acl": "{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}", "options": null, "rls": false}'::jsonb then raise exception 'Internal access preflight drift: feya_commerce_v_seo_keyword_ai_cleanup_report_v1'; end if; execute 'create temporary view feya_internal_expected as  WITH latest_cleanup AS (
         SELECT c.cleanup_id,
            c.run_id,
            c.keyword_id,
            c.keyword_norm,
            c.original_keyword,
            c.cleaned_keyword,
            c.suggested_keyword,
            c.keyword_axis,
            c.keyword_pattern,
            c.suggested_page_level,
            c.ai_intent,
            c.ai_rewrite_status,
            c.should_validate_api,
            c.should_use_for_product,
            c.should_use_for_collection,
            c.should_use_for_image_alt,
            c.should_hold,
            c.warning_flags,
            c.ai_reason,
            c.model_name,
            c.prompt_version,
            c.source_queue_snapshot,
            c.raw_ai_response_json,
            c.review_status,
            c.approved_keyword,
            c.approved_keyword_norm,
            c.approved_at,
            c.approved_by,
            c.created_at,
            c.updated_at,
            row_number() OVER (PARTITION BY c.keyword_norm ORDER BY c.created_at DESC, c.cleanup_id DESC) AS rn
           FROM feya_commerce_seo_keyword_ai_cleanup_v1 c
        ), queue_base AS (
         SELECT q.keyword_id,
            q.keyword,
            q.keyword_norm,
            q.keyword_word_count,
            q.keyword_axis,
            q.keyword_pattern,
            q.product_count,
            q.suggested_page_level,
            q.priority_tier,
            q.validation_priority,
            q.validation_status,
            q.requires_api_validation,
            q.reason,
            q.source,
            q.first_seen_at,
            q.last_seen_at
           FROM feya_commerce_v_seo_api_validation_queue_v1 q
        )
 SELECT qb.keyword_id,
    qb.keyword,
    qb.keyword_norm,
    qb.keyword_word_count,
    qb.keyword_axis AS queue_keyword_axis,
    qb.keyword_pattern AS queue_keyword_pattern,
    qb.product_count,
    qb.suggested_page_level AS queue_suggested_page_level,
    qb.priority_tier,
    qb.validation_priority,
    qb.validation_status,
    qb.requires_api_validation,
    qb.reason AS queue_reason,
    qb.source,
    lc.cleanup_id,
    lc.run_id,
    lc.cleaned_keyword,
    lc.suggested_keyword,
    lc.keyword_axis AS ai_keyword_axis,
    lc.keyword_pattern AS ai_keyword_pattern,
    lc.suggested_page_level AS ai_suggested_page_level,
    lc.ai_intent,
    lc.ai_rewrite_status,
    lc.should_validate_api,
    lc.should_use_for_product,
    lc.should_use_for_collection,
    lc.should_use_for_image_alt,
    lc.should_hold,
    lc.warning_flags,
    lc.ai_reason,
    lc.model_name,
    lc.prompt_version,
    lc.review_status,
    lc.approved_keyword,
    lc.approved_keyword_norm,
    lc.approved_at,
    lc.created_at AS cleanup_created_at,
        CASE
            WHEN (lc.cleanup_id IS NULL) THEN ''needs_ai_cleanup''::text
            WHEN (lc.review_status = ANY (ARRAY[''pending''::text, ''needs_review''::text])) THEN ''needs_human_review''::text
            WHEN lc.should_hold THEN ''hold''::text
            WHEN lc.should_validate_api THEN ''ready_for_metric_validation''::text
            ELSE ''cleaned_no_validation''::text
        END AS cleanup_pipeline_status
   FROM (queue_base qb
     LEFT JOIN latest_cleanup lc ON (((lc.keyword_norm = qb.keyword_norm) AND (lc.rn = 1))));'; execute 'create temporary view feya_internal_actual as '||pg_get_viewdef('public.feya_commerce_v_seo_keyword_ai_cleanup_report_v1'::regclass); if pg_get_viewdef('pg_temp.feya_internal_expected'::regclass) is distinct from pg_get_viewdef('pg_temp.feya_internal_actual'::regclass) then raise exception 'Internal view definition drift: feya_commerce_v_seo_keyword_ai_cleanup_report_v1'; end if; drop view pg_temp.feya_internal_expected; drop view pg_temp.feya_internal_actual; end $g$;

revoke all on public.feya_commerce_v_seo_keyword_ai_cleanup_report_v1 from public,anon,authenticated;

insert into public.feya_commerce_seo_metric_access_contracts_v1 select 'public.feya_commerce_v_seo_keyword_ai_cleanup_report_v1',relkind,md5(pg_get_viewdef(oid)),jsonb_build_object('owner',pg_get_userbyid(relowner),'acl',relacl::text,'options',reloptions,'rls',relrowsecurity) from pg_class where oid='public.feya_commerce_v_seo_keyword_ai_cleanup_report_v1'::regclass;

do $g$ begin if (select jsonb_build_object('owner',pg_get_userbyid(relowner),'acl',relacl::text,'options',reloptions,'rls',relrowsecurity) from pg_class where oid=to_regclass('public.feya_commerce_v_seo_keyword_validation_export_us_en_v1')) is distinct from '{"owner": "postgres", "acl": "{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}", "options": null, "rls": false}'::jsonb then raise exception 'Internal access preflight drift: feya_commerce_v_seo_keyword_validation_export_us_en_v1'; end if; execute 'create temporary view feya_internal_expected as  WITH ranked_queue AS (
         SELECT q.keyword,
            q.keyword_norm,
            q.priority_tier,
            q.keyword_axis,
            q.keyword_pattern,
            q.product_count,
            q.suggested_page_level,
            q.source,
            ''US''::text AS geo,
            ''en''::text AS language,
            ''us_en_tier1_controlled_150''::text AS batch_code,
            row_number() OVER (ORDER BY q.product_count DESC, q.keyword) AS export_rank
           FROM feya_commerce_v_seo_api_validation_queue_v1 q
          WHERE ((q.priority_tier = ''tier_1''::text) AND (q.requires_api_validation IS TRUE) AND (q.keyword_word_count >= 2) AND (q.validation_priority <> ''low''::text) AND (q.keyword_norm <> ALL (ARRAY[''full set''::text, ''whole product''::text, ''choose your set''::text, ''полный комплект''::text])) AND (q.keyword_norm !~ ''(^|[^a-z0-9])(xxs|xs|s us|m us|l us|xl|2x|3x|size|размер|буквенный)([^a-z0-9]|$)''::text))
        )
 SELECT keyword,
    keyword_norm,
    priority_tier,
    keyword_axis,
    keyword_pattern,
    product_count,
    suggested_page_level,
    source,
    geo,
    language,
    batch_code,
    export_rank
   FROM ranked_queue
  WHERE (export_rank <= 150);'; execute 'create temporary view feya_internal_actual as '||pg_get_viewdef('public.feya_commerce_v_seo_keyword_validation_export_us_en_v1'::regclass); if pg_get_viewdef('pg_temp.feya_internal_expected'::regclass) is distinct from pg_get_viewdef('pg_temp.feya_internal_actual'::regclass) then raise exception 'Internal view definition drift: feya_commerce_v_seo_keyword_validation_export_us_en_v1'; end if; drop view pg_temp.feya_internal_expected; drop view pg_temp.feya_internal_actual; end $g$;

revoke all on public.feya_commerce_v_seo_keyword_validation_export_us_en_v1 from public,anon,authenticated;

insert into public.feya_commerce_seo_metric_access_contracts_v1 select 'public.feya_commerce_v_seo_keyword_validation_export_us_en_v1',relkind,md5(pg_get_viewdef(oid)),jsonb_build_object('owner',pg_get_userbyid(relowner),'acl',relacl::text,'options',reloptions,'rls',relrowsecurity) from pg_class where oid='public.feya_commerce_v_seo_keyword_validation_export_us_en_v1'::regclass;

create or replace function public.feya_commerce_metric_access_boundary_health_v1() returns text
language plpgsql stable security invoker set search_path=pg_catalog,public,pg_temp as $access$
declare r record; c record; current_oids oid[]; registered_oids oid[];
begin
 if (select count(*) from public.feya_commerce_seo_metric_access_contracts_v1)<>57 or (select count(*) from public.feya_commerce_seo_metric_access_contracts_v1 where object_kind='r')<>2 then return null; end if;
 with recursive closure(oid) as (
  select to_regclass(object_identity)::oid from public.feya_commerce_seo_metric_access_contracts_v1 where object_kind='r' or object_identity in ('public.feya_commerce_v_keyword_cleanup_review_status_safe_v1','public.feya_commerce_v_page_ownership_shortlist_v1','public.feya_commerce_v_page_query_ownership_candidate_clusters_v1','public.feya_commerce_v_seo_keyword_ai_cleanup_report_v1','public.feya_commerce_v_keyword_cleanup_review_risk_v1','public.feya_commerce_v_seo_api_validation_queue_v1')
  union select rw.ev_class from closure t join pg_depend d on d.refobjid=t.oid and d.refclassid='pg_class'::regclass and d.classid='pg_rewrite'::regclass
  join pg_rewrite rw on rw.oid=d.objid join pg_class v on v.oid=rw.ev_class where v.relkind in ('v','m') and v.oid<>t.oid
 ) select array_agg(oid order by oid) into current_oids from closure;
 select array_agg(to_regclass(object_identity)::oid order by to_regclass(object_identity)::oid) into registered_oids from public.feya_commerce_seo_metric_access_contracts_v1;
 if current_oids is distinct from registered_oids then return null; end if;
 for r in select * from public.feya_commerce_seo_metric_access_contracts_v1 loop
  select * into c from pg_class where oid=to_regclass(r.object_identity);
  if not found or c.relkind::text<>r.object_kind then return null; end if;
  if has_table_privilege('anon',c.oid,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER')
   or has_table_privilege('authenticated',c.oid,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER')
   or not has_table_privilege('service_role',c.oid,'SELECT') then return null; end if;
  if jsonb_build_object('owner',pg_get_userbyid(c.relowner),'acl',c.relacl::text,'options',c.reloptions,'rls',c.relrowsecurity) is distinct from r.metadata_json then return null; end if;
  if r.object_kind='v' and md5(pg_get_viewdef(c.oid)) is distinct from r.definition_md5 then return null; end if;
 end loop;
 if (select jsonb_build_object('owner',pg_get_userbyid(proowner),'acl',proacl::text,'prosecdef',prosecdef,'proconfig',proconfig,'body_md5',md5(prosrc)) from pg_proc where oid=to_regprocedure('public.feya_fn_content_jaccard_v1(text[],text[])')) is distinct from '{"owner": "postgres", "acl": "{postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}", "prosecdef": false, "proconfig": ["search_path=\"\""], "body_md5": "66a7b41f847555413676c41ca2982f2f"}'::jsonb then return null; end if;
 if (select jsonb_build_object('owner',pg_get_userbyid(proowner),'acl',proacl::text,'prosecdef',prosecdef,'proconfig',proconfig,'body_md5',md5(prosrc)) from pg_proc where oid=to_regprocedure('public.feya_fn_content_token_set_v1(text)')) is distinct from '{"owner": "postgres", "acl": "{postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}", "prosecdef": false, "proconfig": ["search_path=\"\""], "body_md5": "acaa99ac79c595ab6bd9e867a56af000"}'::jsonb then return null; end if;
 return 'metric_access_boundary_v2';
end $access$;

do $g$ begin if public.feya_commerce_metric_access_boundary_health_v1() is distinct from 'metric_access_boundary_v2' or public.feya_commerce_metric_reader_boundary_health_v1() is distinct from 'metric_reader_boundary_v1' then raise exception 'Extended access postcondition failed'; end if; end $g$;

commit;
