-- Generated by scripts/build-metric-function-hardening.py. NOT applied to production.

-- Requires atomic-import + reader-boundary migrations. No ACL, RLS, body or business-data change.

-- Fixed trusted path; every business relation in these four bodies is schema-qualified.

begin;

set local search_path=pg_catalog,pg_temp;

do $health$ begin if public.feya_commerce_metric_reader_boundary_health_v1() is distinct from 'metric_reader_boundary_v1' then raise exception 'Reader contract unhealthy; no function settings changed'; end if; end $health$;

do $guard$ begin
  if (select jsonb_build_object('owner',pg_get_userbyid(proowner),'acl',proacl::text,
    'security_definer',prosecdef,'options',proconfig,'body_md5',md5(prosrc))
    from pg_proc where oid=to_regprocedure('public.feya_commerce_apply_seo_keyword_metric_import_v1(text,text)'))
    is distinct from '{"owner": "postgres", "acl": "{postgres=X/postgres,service_role=X/postgres}", "security_definer": true, "options": ["search_path=public"], "body_md5": "39993c89e561ab0344fb3d074f78550c"}'::jsonb
  then raise exception 'Function hardening preflight drift: feya_commerce_apply_seo_keyword_metric_import_v1(text,text)'; end if;
end $guard$;

do $guard$ begin
  if (select jsonb_build_object('owner',pg_get_userbyid(proowner),'acl',proacl::text,
    'security_definer',prosecdef,'options',proconfig,'body_md5',md5(prosrc))
    from pg_proc where oid=to_regprocedure('public.feya_commerce_fn_promote_keyword_metric_import_v1(text)'))
    is distinct from '{"owner": "postgres", "acl": "{postgres=X/postgres,service_role=X/postgres}", "security_definer": true, "options": null, "body_md5": "baeef13d9b43c164230e34c8df5b92b3"}'::jsonb
  then raise exception 'Function hardening preflight drift: feya_commerce_fn_promote_keyword_metric_import_v1(text)'; end if;
end $guard$;

do $guard$ begin
  if (select jsonb_build_object('owner',pg_get_userbyid(proowner),'acl',proacl::text,
    'security_definer',prosecdef,'options',proconfig,'body_md5',md5(prosrc))
    from pg_proc where oid=to_regprocedure('public.feya_fn_apply_manual_keyword_metrics_v1(text)'))
    is distinct from '{"owner": "postgres", "acl": "{postgres=X/postgres,service_role=X/postgres}", "security_definer": true, "options": null, "body_md5": "fd72199909453f2f02038f238698cde6"}'::jsonb
  then raise exception 'Function hardening preflight drift: feya_fn_apply_manual_keyword_metrics_v1(text)'; end if;
end $guard$;

do $guard$ begin
  if (select jsonb_build_object('owner',pg_get_userbyid(proowner),'acl',proacl::text,
    'security_definer',prosecdef,'options',proconfig,'body_md5',md5(prosrc))
    from pg_proc where oid=to_regprocedure('public.seo_keyword_bank_v1_set_updated_at()'))
    is distinct from '{"owner": "postgres", "acl": "{=X/postgres,postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}", "security_definer": false, "options": null, "body_md5": "9b1889f56258bf9d6554213c05019c76"}'::jsonb
  then raise exception 'Function hardening preflight drift: seo_keyword_bank_v1_set_updated_at()'; end if;
end $guard$;

alter function public.feya_commerce_apply_seo_keyword_metric_import_v1(text,text) set search_path to pg_catalog, pg_temp;

alter function public.feya_commerce_fn_promote_keyword_metric_import_v1(text) set search_path to pg_catalog, pg_temp;

alter function public.feya_fn_apply_manual_keyword_metrics_v1(text) set search_path to pg_catalog, pg_temp;

alter function public.seo_keyword_bank_v1_set_updated_at() set search_path to pg_catalog, pg_temp;

do $guard$ begin
  if (select jsonb_build_object('owner',pg_get_userbyid(proowner),'acl',proacl::text,
    'security_definer',prosecdef,'options',proconfig,'body_md5',md5(prosrc))
    from pg_proc where oid=to_regprocedure('public.feya_commerce_apply_seo_keyword_metric_import_v1(text,text)'))
    is distinct from '{"owner": "postgres", "acl": "{postgres=X/postgres,service_role=X/postgres}", "security_definer": true, "options": ["search_path=pg_catalog, pg_temp"], "body_md5": "39993c89e561ab0344fb3d074f78550c"}'::jsonb
  then raise exception 'Function hardening preflight drift: feya_commerce_apply_seo_keyword_metric_import_v1(text,text)'; end if;
end $guard$;

do $guard$ begin
  if (select jsonb_build_object('owner',pg_get_userbyid(proowner),'acl',proacl::text,
    'security_definer',prosecdef,'options',proconfig,'body_md5',md5(prosrc))
    from pg_proc where oid=to_regprocedure('public.feya_commerce_fn_promote_keyword_metric_import_v1(text)'))
    is distinct from '{"owner": "postgres", "acl": "{postgres=X/postgres,service_role=X/postgres}", "security_definer": true, "options": ["search_path=pg_catalog, pg_temp"], "body_md5": "baeef13d9b43c164230e34c8df5b92b3"}'::jsonb
  then raise exception 'Function hardening preflight drift: feya_commerce_fn_promote_keyword_metric_import_v1(text)'; end if;
end $guard$;

do $guard$ begin
  if (select jsonb_build_object('owner',pg_get_userbyid(proowner),'acl',proacl::text,
    'security_definer',prosecdef,'options',proconfig,'body_md5',md5(prosrc))
    from pg_proc where oid=to_regprocedure('public.feya_fn_apply_manual_keyword_metrics_v1(text)'))
    is distinct from '{"owner": "postgres", "acl": "{postgres=X/postgres,service_role=X/postgres}", "security_definer": true, "options": ["search_path=pg_catalog, pg_temp"], "body_md5": "fd72199909453f2f02038f238698cde6"}'::jsonb
  then raise exception 'Function hardening preflight drift: feya_fn_apply_manual_keyword_metrics_v1(text)'; end if;
end $guard$;

do $guard$ begin
  if (select jsonb_build_object('owner',pg_get_userbyid(proowner),'acl',proacl::text,
    'security_definer',prosecdef,'options',proconfig,'body_md5',md5(prosrc))
    from pg_proc where oid=to_regprocedure('public.seo_keyword_bank_v1_set_updated_at()'))
    is distinct from '{"owner": "postgres", "acl": "{=X/postgres,postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}", "security_definer": false, "options": ["search_path=pg_catalog, pg_temp"], "body_md5": "9b1889f56258bf9d6554213c05019c76"}'::jsonb
  then raise exception 'Function hardening preflight drift: seo_keyword_bank_v1_set_updated_at()'; end if;
end $guard$;

-- Rebaseline ONLY the three reviewed function settings; retain all 14 view contracts.
do $refresh$ declare changed integer; begin
  update public.feya_commerce_seo_metric_reader_contracts_v1 m set
    definition_md5=md5(pg_get_functiondef(p.oid)),
    metadata_json=jsonb_build_object('owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'options',p.proconfig)
  from pg_proc p where m.object_kind='function' and m.object_identity in ('public.feya_commerce_apply_seo_keyword_metric_import_v1(text,text)','public.feya_commerce_fn_promote_keyword_metric_import_v1(text)','public.feya_fn_apply_manual_keyword_metrics_v1(text)')
    and p.oid=to_regprocedure(m.object_identity);
  get diagnostics changed = row_count;
  if changed<>3 then raise exception 'Unexpected reader manifest update count'; end if;
end $refresh$;

do $health$ begin if public.feya_commerce_metric_reader_boundary_health_v1() is distinct from 'metric_reader_boundary_v1' then raise exception 'Reader contract unhealthy; no function settings changed'; end if; end $health$;

commit;
